{% set version = "9.1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggblanket
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggblanket_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggblanket/ggblanket_{{ version }}.tar.gz
  sha256: 1e1e892c49004b6a5103db313e28ff6394c50d20b7a715a56b99506ffa34cbda

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-colorspace
    - r-dplyr >=1.0.4
    - r-farver
    - r-forcats
    - r-ggplot2 >=3.5.0
    - r-hms >=0.5.0
    - r-labelled
    - r-lubridate >=1.7.8
    - r-magrittr
    - r-purrr
    - r-rlang >=1.1.0
    - r-scales >=1.3.0
    - r-snakecase
    - r-stringr >=1.3.0
    - r-tidyr >=1.0.0
    - r-tidyselect >=1.2.0
    - r-viridislite
  run:
    - r-base
    - r-colorspace
    - r-dplyr >=1.0.4
    - r-farver
    - r-forcats
    - r-ggplot2 >=3.5.0
    - r-hms >=0.5.0
    - r-labelled
    - r-lubridate >=1.7.8
    - r-magrittr
    - r-purrr
    - r-rlang >=1.1.0
    - r-scales >=1.3.0
    - r-snakecase
    - r-stringr >=1.3.0
    - r-tidyr >=1.0.0
    - r-tidyselect >=1.2.0
    - r-viridislite

test:
  commands:
    - $R -e "library('ggblanket')"           # [not win]
    - "\"%R%\" -e \"library('ggblanket')\""  # [win]

about:
  home: https://github.com/davidhodge931/ggblanket/, https://davidhodge931.github.io/ggblanket/
  license: MIT
  summary: Simplify 'ggplot2' visualisation with 'ggblanket' wrapper functions.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
