{% set version = "4.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggblanket
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggblanket_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggblanket/ggblanket_{{ version }}.tar.gz
  sha256: 473d7ec373ccb83bb8aa15418fa1708a60e86c487854140221f7aba2cb38c5d6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-hms
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-scales
    - r-snakecase
    - r-tidyr
    - r-tidyselect
    - r-viridis
  run:
    - r-base
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-hms
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-scales
    - r-snakecase
    - r-tidyr
    - r-tidyselect
    - r-viridis

test:
  commands:
    - $R -e "library('ggblanket')"           # [not win]
    - "\"%R%\" -e \"library('ggblanket')\""  # [win]

about:
  home: https://github.com/davidhodge931/ggblanket/, https://davidhodge931.github.io/ggblanket/
  license: MIT
  summary: Wrapper functions around the amazing 'ggplot2' package with the objective to make beautiful 'ggplot2' visualisation simpler.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
