{% set version = "21.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggblanket
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggblanket_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggblanket/ggblanket_{{ version }}.tar.gz
  sha256: 47c6dcccb95a71b29029fc6ff25a0ac7b628eaaca82c05a903d9f513715ca2d5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-blends
    - r-farver
    - r-ggnewscale >=0.5.2
    - r-ggplot2 >=4.0.0
    - r-ggrefine
    - r-jumble
    - r-purrr
    - r-rlang
    - r-scales >=1.4.0
    - r-snakecase
    - r-stringr
    - r-viridis
  run:
    - r-base
    - r-blends
    - r-farver
    - r-ggnewscale >=0.5.2
    - r-ggplot2 >=4.0.0
    - r-ggrefine
    - r-jumble
    - r-purrr
    - r-rlang
    - r-scales >=1.4.0
    - r-snakecase
    - r-stringr
    - r-viridis

test:
  commands:
    - $R -e "library('ggblanket')"           # [not win]
    - "\"%R%\" -e \"library('ggblanket')\""  # [win]

about:
  home: https://davidhodge931.github.io/ggblanket/
  dev_url: https://github.com/davidhodge931/ggblanket/
  license: MIT
  summary: Wrapper 'ggplot2' functions for publication-quality visualisation. Aligned with 'ggplot2' and 'tidyverse'. Covers much of what 'ggplot2' does.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
